---
title: "Impacts of Broadband Development on Rural Property Values"
---


# **Goal**
Evaluate the effectiveness of United States Department of Agriculture (USDA) broadband initiatives with respect to rural property values and internet speed.
<br>
The USDA would like to quantify the impact of its investments into broadband infrastructure nationally. This study aims to devise a novel statistical methodology that allows for broadband program evaluation. 
<br>
Our work on this project concerned the effect of broadband programs on two specific variables, internet speeds and assessed property values. 


## **Project Sponsor**
The sponsor of this project is the USDA Economic Research Service, and our stakeholder is John Pender, senior economist.

# **Method**
##Hedonic Regression Model 
Housing prices were modelled with a hedonic regression model. Different characteristics of each property such as square footage, bedrooms, and bathrooms were evaluated for the effect on house prices so that we could isolate the effects of the program.

##Difference in Differences 
To illustrate the effects of the program on internet speeds and housing prices, we implemented difference in differences by including indicators for time elapsed, position relative to project border, and the interaction between the two.
  






<!-- Here's how you make a list: -->

<!-- *Tips for making figures look good:* -->

<!-- - Make text sizes BIG -->
<!-- - Stick to the same colors -->
<!-- - Decide to add titles, captions, etc in the figures OR add on the website for all figures -->

